pipeline
{
    agent
    {
        label 'control'
    }

    stages
    {
        stage('create-file')
        {
            
            steps{
                   sh '''
                   cd aws
                   terraform init
                   terraform plan
                   terraform apply -auto-approve
                   '''
               }
        
        }
        
    }
}